apiVersion: apps/v1         # Deployment の API バージョン。kubectl api-resources | grep Deployment と kubectl api-versions  | grep apps で確認可能  
kind: Deployment            # デプロイメント定義ファイルであることを明示
metadata:
  name: nginx-pod           # 識別名
spec:
  replicas: 3               # Pod の数
  selector:
    matchLabels:
      app: nginx-server     # template:metadata:labels:app と同じ値にする必要がある
  template:
    metadata:
      labels:               # Pod をクラスタ内で識別のするためのラベル
        app: nginx-server   # 識別名。selector:matchLabels:app と同じ値にする必要がある
    spec:
      containers:           # Pod 内で動作させるコンテナ群の設定
      - image: techeten/nginx             # Container Registry にアップロードした docker image
        name: nginx-container             # コンテナ名
        ports:
        - containerPort: 80
          name: http-server
