apiVersion: v1
kind: Pod
metadata:
  name: sample-gpu-pod
  labels:
    app: sample-gpu-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: sample-gpu-container
    image: gcr.io/my-project2-303004/sample-image
    ports:
    - containerPort: 80
      name: http-server
#    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
