version: '2.3'

services:
    sample_server:
        container_name: pipeline_container
        image: pipeline-image
        build:
            context: "."
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
            #command: bash -c "python3 download_dataset_from_gcs.py --debug"
